INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1771986826764, 'Others', 'Universal Speaker Wire(2P)', '차량의 스피커 컨넥터에 꽂아서 사용하는 범용 스피커 컨넥터', '', 5000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Universal%20Speaker%20Wire(2P).jpg', '[]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1772431121062, 'PnP Cable - DSP', 'DS-C80-6B', 'C80-88 전용 PnP / 전면6채널+서브우퍼2채널용 / 케이블길이 1.5M', 'B타입 / DSP측 케이블', 180000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/DS-82B-2.jpg', '[{"id":1772431021599.1846,"type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/DS-C80-6B.jpg"}]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1772683222883, 'Others', 'DPS-25M-Uni Baffle', 'DPS-25M을 장착하기 위한 범용 스피커 가이드', '', 20000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/DPS-25M-Uni%20Baffle-01.jpg', '[{"id":1772682878156.417,"type":"text","value":"별도의 부자재나 공구 없이 DPS-25M과 결합되며, 스크류홀 가이드는 최대 30도까지 회전됩니다."},{"id":1772683044685.372,"type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/DPS-25M-Uni%20Baffle-02.jpg"},{"id":1772683064566.309,"type":"text","value":"스크류 홀 가이드의 길이는 필요에 따라 홈을 쉽게 잘라낼 수 있습니다."},{"id":1772683109623.2285,"type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/DPS-25M-Uni%20Baffle-03.jpg"}]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1773363359421, 'Others', 'Speaker Connector A', '현대 기아 제네시스 미드우퍼 스피커 컨넥터', '.', 8000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20A.jpg', '[{"id":"1773363594097773388","type":"text","value":"크렐/렉시콘/BOSE/JBL은 약간 다를 수 있습니다. 차량 컨넥터의 돌기를 제거하고 사용하면 됩니다."},{"id":"1773366659684604120","type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20A-01.jpg"},{"id":"1773366669904969540","type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20A-02.jpg"}]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1773363728266, 'Others', 'Speaker Connector B', '현대 기아 제네시스 트위터/미드레인지 스피커 컨넥터', '.', 8000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20B.jpg', '[{"id":"1773366834332364874","type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20B-01.jpg"},{"id":"1773366844288389257","type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20B-02.jpg"}]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1773363790940, 'Others', 'Speaker Connector C', '현대 기아 제네시스 트위터/미드레인지/센터 스피커 컨넥터', '.', 8000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20C.jpg', '[{"id":"1773367004429412301","type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20C-01.jpg"},{"id":"1773367021917163355","type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20C-02.jpg"}]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1773363904936, 'Others', 'Speaker Connector D', 'KGM 신형 스피커 컨넥터 / 현대 기아 구형 스피커 컨넥터', '.', 8000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20D.jpg', '[{"id":"1773367205759369869","type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20D-01.jpg"},{"id":"1773367216395525632","type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20D-02.jpg"}]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1773363956072, 'Others', 'Speaker Connector E', 'KGM 렉스턴/칸/무쏘 미드우퍼 컨넥터', '.', 8000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20E.jpg', '[{"id":"1773368084320875338","type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20E-01.jpg"},{"id":"1773368095612193704","type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/Speaker%20Connector%20E-02.jpg"}]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1773388000237, 'Speakers', 'S2-W8D그릴 (KTE-8G.3)', '.', '.', 50000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/KTE-8G.3 (S2-W8D그릴).jpg', '[]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1773388147415, 'Speakers', 'S2-W10D그릴 (KTE-10G.3)', '.', '.', 50000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/KTE-10G.3 (S2-W10D그릴).jpg', '[]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;