INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1770600682237, 'PnP Cable - 기타 (Other)', 'PXE-M770 External Cable(8M)', '', '.', 60000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/M770%20EX.jpg', '[]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1770603575697, 'PnP Cable - 기타수입차 (Other Imported Cars)', 'TS-301', 'KCU-TSL21M3-1 / Tesla 11채널 스탠다드 / 21년 이전 / Model3 ModelY / PXE-X121-12EV와 연결', 'AB타입', 390000, 'assets/images/TS-301.jpg', '[]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1770603638565, 'PnP Cable - 기타수입차 (Other Imported Cars)', 'TS-302', 'KCU-TSL22M3-1 / Tesla 11채널 스탠다드 / 22년~24년 / Model3 ModelY / PXE-X121-12EV와 연결', 'AB타입', 390000, 'assets/images/TS-301.jpg', '[]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1770603681161, 'PnP Cable - 기타수입차 (Other Imported Cars)', 'TS-303', 'KCU-TSL21MY-1 / Tesla 13채널 롱레인지 / 21년 이전 / Model3 ModelY / PXE-X121-12EV와 연결', 'AB타입', 390000, 'assets/images/TS-301.jpg', '[]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1770603735895, 'PnP Cable - 기타수입차 (Other Imported Cars)', 'TS-304', 'KCU-TSL22MY-1 / Tesla 13채널 롱레인지 / 22년~24년 / Model3 ModelY / PXE-X121-12EV와 연결', 'AB타입', 390000, 'assets/images/TS-301.jpg', '[]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1770778417150, 'PnP Cable - 독일차 (German Cars)', 'VW-1A', '폭스바겐 4CH 14년 이후 자출', 'A타입 / 차측용 케이블 2M', 230000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/VW-1A.jpg', '[{"id":"1771329034194.1387","type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/VW-1A-C.jpg"}]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1770778453204, 'PnP Cable - 기타수입차 (Other Imported Cars)', 'CH-1A', '4CH 22년 이후 자출', 'A타입 / 차측용 케이블', 230000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/CH-1A.jpg', '[{"id":1771329584107.2905,"type":"image","value":"https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/CH-1A-C.jpg"}]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1770988034579, 'PnP Cable - 국산차 (Domestic)', 'GE-203', 'G80 Actune(24년이전)/케이블길이 2M / PXE-C80-88과 연결', 'AB타입', 150000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/GE-203.jpg', '[]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1771985617838, 'PnP Cable - 국산차 (Domestic)', 'KG-1A', 'KGM 차량의 알파인 오디오 옵션 차량', 'A타입 / 차측용 케이블', 70000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/KG-1A.jpg', '[]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO "alpine-home".products (id, category, title, description, desc_bottom, price, image, detail_blocks, attachments, manual_url) VALUES (1771985839541, 'Others', 'KGM 5.5" to 6.5" 배플', 'KGM 5.5"스피커를 6.5"로 변경하는 스피커 가이드
(무쏘EV,액티언, 토레스)', '', 20000, 'https://raw.githubusercontent.com/alpinehome-jcha/alpinehompage/main/assets/images/KGM 5.5 to 6.5 배플.jpg', '[]'::jsonb, '[]'::jsonb, NULL) ON CONFLICT (id) DO NOTHING;