server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 50M;

    location /api/health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'OK';
    }

    location / {
        try_files $uri $uri/ $uri.html /index.html =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
