-- SQL Script to create the `service_management` table in Supabase
-- Please copy and paste this into the Supabase SQL Editor and run it.

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.service_management (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receive_date DATE,
    status VARCHAR(50),
    customer_name VARCHAR(100),
    address TEXT,
    vehicle_info VARCHAR(255),
    reserve_date DATE,
    car_model VARCHAR(100),
    phone VARCHAR(50),
    symptom TEXT,
    method TEXT,
    complete_date DATE,
    manager VARCHAR(100),
    cost VARCHAR(50),      -- Storing as string to keep comma formatting, or can be numeric
    recovery_status VARCHAR(50), -- 고품회수여부
    failure_cause VARCHAR(255),  -- 고장원인
    details TEXT,
    images JSONB,                -- 첨부 이미지 목록 저장 (배열)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Turn on Row Level Security (RLS)
ALTER TABLE public.service_management ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy that allows anyone to read/write (anon key full CRUD)
DROP POLICY IF EXISTS "Allow anonymous read access" ON public.service_management;
DROP POLICY IF EXISTS "Allow anonymous insert access" ON public.service_management;
DROP POLICY IF EXISTS "Allow anonymous update access" ON public.service_management;
DROP POLICY IF EXISTS "Allow anonymous delete access" ON public.service_management;

CREATE POLICY "Allow anonymous read access" ON public.service_management FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert access" ON public.service_management FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous update access" ON public.service_management FOR UPDATE USING (true);
CREATE POLICY "Allow anonymous delete access" ON public.service_management FOR DELETE USING (true);

-- If the table already exists, you can run these ALTER commands directly:
-- ALTER TABLE public.service_management ADD COLUMN IF NOT EXISTS failure_cause VARCHAR(255);
-- ALTER TABLE public.service_management ADD COLUMN IF NOT EXISTS images JSONB;

-- End of script
