-- SQL Script to create the `service_management` table in Supabase
-- Please copy and paste this into the Supabase SQL Editor and run it.

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.service_management (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receive_date DATE,
    status VARCHAR(50),
    customer_name VARCHAR(100),
    address TEXT,
    vehicle_info VARCHAR(255),
    reserve_date DATE,
    car_model VARCHAR(100),
    phone VARCHAR(50),
    symptom TEXT,
    method TEXT,
    complete_date DATE,
    manager VARCHAR(100),
    cost VARCHAR(50),      -- Storing as string to keep comma formatting, or can be numeric
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Turn on Row Level Security (RLS)
ALTER TABLE public.service_management ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy that allows anyone to read (if you want dealers to see it, or keep it admin only)
-- For this feature, since the UI is protected by auth.js admin check, we can allow full access for now, 
-- or we can restrict it if needed. Because the website relies on a shared anon key and custom RPC auth, 
-- standard Supabase auth is bypassed. So we will just allow anon key to do full CRUD, but the UI protects it.

CREATE POLICY "Allow anonymous read access" ON public.service_management FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert access" ON public.service_management FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous update access" ON public.service_management FOR UPDATE USING (true);
CREATE POLICY "Allow anonymous delete access" ON public.service_management FOR DELETE USING (true);

-- End of script
